import { IPhotoCollection } from '@siddhesh-savant-photography/models';

export const featuredCollections = () =>
  [
    {
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/featured/ELLE DECOR/ELLE_DECOR_Cover.PNG',
      thumbnailAltText: 'ELLE_DECOR_Cover.PNG',
      description: '',
      eager: false,
      width: 2164,
      height: 2880,
      photos: [
        {
          id: '0',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/featured/ELLE DECOR/ELLE_DECOR_Cover.PNG',
          altText: 'ELLE_DECOR_Cover.PNG',
          width: 2164,
          height: 2880,
        },
        {
          id: '1',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/featured/ELLE DECOR/ELLE_DECOR_ISIMG-763944.JPG',
          altText: 'ELLE_DECOR_ISIMG-763944.JPG',
          width: 2223,
          height: 2778,
        },
        {
          id: '2',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/featured/ELLE DECOR/ELLE_DECOR_ISIMG-764268.JPG',
          altText: 'ELLE_DECOR_ISIMG-764268.JPG',
          width: 2223,
          height: 2778,
        },
        {
          id: '3',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/featured/ELLE DECOR/ELLE_DECOR_ISIMG-764450.JPG',
          altText: 'ELLE_DECOR_ISIMG-764450.JPG',
          width: 2223,
          height: 2778,
        },
        {
          id: '4',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/featured/ELLE DECOR/ELLE_DECOR_ISIMG-764968.JPG',
          altText: 'ELLE_DECOR_ISIMG-764968.JPG',
          width: 2223,
          height: 2778,
        },
        {
          id: '5',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/featured/ELLE DECOR/ELLE_DECOR_ISIMG-765194.JPG',
          altText: 'ELLE_DECOR_ISIMG-765194.JPG',
          width: 2223,
          height: 2778,
        },
        {
          id: '6',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/featured/ELLE DECOR/ELLE_DECOR_ISIMG-765297.JPG',
          altText: 'ELLE_DECOR_ISIMG-765297.JPG',
          width: 2223,
          height: 2778,
        },
        {
          id: '7',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/featured/ELLE DECOR/ELLE_DECOR_ISIMG-765338.JPG',
          altText: 'ELLE_DECOR_ISIMG-765338.JPG',
          width: 2223,
          height: 2778,
        },
        {
          id: '8',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/featured/ELLE DECOR/ELLE_DECOR_ISIMG-765619.JPG',
          altText: 'ELLE_DECOR_ISIMG-765619.JPG',
          width: 2223,
          height: 2778,
        },
        {
          id: '9',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/featured/ELLE DECOR/ELLE_DECOR_ISIMG-767455.JPG',
          altText: 'ELLE_DECOR_ISIMG-767455.JPG',
          width: 2223,
          height: 2778,
        },
        {
          id: '10',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/featured/ELLE DECOR/ELLE_DECOR_ISIMG-768176.JPG',
          altText: 'ELLE_DECOR_ISIMG-768176.JPG',
          width: 2223,
          height: 2778,
        },
        {
          id: '11',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/featured/ELLE DECOR/ELLE_DECOR_ISIMG-768374.JPG',
          altText: 'ELLE_DECOR_ISIMG-768374.JPG',
          width: 2223,
          height: 2778,
        },
        {
          id: '12',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/featured/ELLE DECOR/ELLE_DECOR_ISIMG-768390.JPG',
          altText: 'ELLE_DECOR_ISIMG-768390.JPG',
          width: 2223,
          height: 2778,
        },
        {
          id: '13',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/featured/ELLE DECOR/ELLE_DECOR_ISIMG-768932.JPG',
          altText: 'ELLE_DECOR_ISIMG-768932.JPG',
          width: 2223,
          height: 2778,
        },
      ],
      previous: { collectionId: '1', title: 'Good Homes' },
      next: { collectionId: '1', title: 'Good Homes' },
      collectionId: '0',
      title: 'Elle Decor',
    },
    {
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/featured/Good Homes__June - July \u002723/Good_Homes_COVER.png',
      thumbnailAltText: 'Good_Homes_COVER.png',
      description: 'June - July \u002723',
      eager: false,
      width: 2119,
      height: 2668,
      photos: [
        {
          id: '0',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/featured/Good Homes__June - July \u002723/Good_Homes_COVER.png',
          altText: 'Good_Homes_COVER.png',
          width: 2119,
          height: 2668,
        },
        {
          id: '1',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/featured/Good Homes__June - July \u002723/Good_Homes_Screenshot 2024-05-15 at 6.32.14 PM.png',
          altText: 'Good_Homes_Screenshot 2024-05-15 at 6.32.14 PM.png',
          width: 4258,
          height: 2664,
        },
        {
          id: '2',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/featured/Good Homes__June - July \u002723/Good_Homes_Screenshot 2024-05-15 at 6.33.09 PM.png',
          altText: 'Good_Homes_Screenshot 2024-05-15 at 6.33.09 PM.png',
          width: 4249,
          height: 2658,
        },
        {
          id: '3',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/featured/Good Homes__June - July \u002723/Good_Homes_Screenshot 2024-05-15 at 6.33.22 PM.png',
          altText: 'Good_Homes_Screenshot 2024-05-15 at 6.33.22 PM.png',
          width: 4261,
          height: 2664,
        },
        {
          id: '4',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/featured/Good Homes__June - July \u002723/Good_Homes_Screenshot 2024-05-15 at 6.33.36 PM.png',
          altText: 'Good_Homes_Screenshot 2024-05-15 at 6.33.36 PM.png',
          width: 4069,
          height: 2668,
        },
      ],
      previous: { collectionId: '0', title: 'ELLE DECOR' },
      next: { collectionId: '0', title: 'ELLE DECOR' },
      collectionId: '1',
      title: 'Good Homes',
    },
  ] as IPhotoCollection[];
