import { IPhotoCollection } from '@siddhesh-savant-photography/models';

export const homeAndSpacesCollections = () =>
  [
    {
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/CLUB AMSTORIA/CLUB_AMSTORIA_COVER.jpg',
      thumbnailAltText: 'CLUB_AMSTORIA_COVER.jpg',
      description: '',
      eager: false,
      width: 1920,
      height: 1280,
      photos: [
        {
          id: '0',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/CLUB AMSTORIA/CLUB_AMSTORIA_COVER.jpg',
          altText: 'CLUB_AMSTORIA_COVER.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '1',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/CLUB AMSTORIA/CLUB_AMSTORIA_IMG_6633.jpg',
          altText: 'CLUB_AMSTORIA_IMG_6633.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '2',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/CLUB AMSTORIA/CLUB_AMSTORIA_IMG_6641.jpg',
          altText: 'CLUB_AMSTORIA_IMG_6641.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '3',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/CLUB AMSTORIA/CLUB_AMSTORIA_IMG_6668.jpg',
          altText: 'CLUB_AMSTORIA_IMG_6668.jpg',
          width: 1920,
          height: 1263,
        },
        {
          id: '4',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/CLUB AMSTORIA/CLUB_AMSTORIA_IMG_6683.jpg',
          altText: 'CLUB_AMSTORIA_IMG_6683.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '5',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/CLUB AMSTORIA/CLUB_AMSTORIA_IMG_6684.jpg',
          altText: 'CLUB_AMSTORIA_IMG_6684.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '6',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/CLUB AMSTORIA/CLUB_AMSTORIA_IMG_6698.jpg',
          altText: 'CLUB_AMSTORIA_IMG_6698.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '7',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/CLUB AMSTORIA/CLUB_AMSTORIA_IMG_6701.jpg',
          altText: 'CLUB_AMSTORIA_IMG_6701.jpg',
          width: 1920,
          height: 1263,
        },
        {
          id: '8',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/CLUB AMSTORIA/CLUB_AMSTORIA_IMG_6703.jpg',
          altText: 'CLUB_AMSTORIA_IMG_6703.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '9',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/CLUB AMSTORIA/CLUB_AMSTORIA_IMG_6706.jpg',
          altText: 'CLUB_AMSTORIA_IMG_6706.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '10',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/CLUB AMSTORIA/CLUB_AMSTORIA_IMG_6711.jpg',
          altText: 'CLUB_AMSTORIA_IMG_6711.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '11',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/CLUB AMSTORIA/CLUB_AMSTORIA_IMG_6715.jpg',
          altText: 'CLUB_AMSTORIA_IMG_6715.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '12',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/CLUB AMSTORIA/CLUB_AMSTORIA_IMG_6716.jpg',
          altText: 'CLUB_AMSTORIA_IMG_6716.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '13',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/CLUB AMSTORIA/CLUB_AMSTORIA_IMG_6723.jpg',
          altText: 'CLUB_AMSTORIA_IMG_6723.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '14',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/CLUB AMSTORIA/CLUB_AMSTORIA_IMG_6727.jpg',
          altText: 'CLUB_AMSTORIA_IMG_6727.jpg',
          width: 1920,
          height: 1263,
        },
        {
          id: '15',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/CLUB AMSTORIA/CLUB_AMSTORIA_IMG_6732.jpg',
          altText: 'CLUB_AMSTORIA_IMG_6732.jpg',
          width: 1920,
          height: 1263,
        },
        {
          id: '16',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/CLUB AMSTORIA/CLUB_AMSTORIA_IMG_6734.jpg',
          altText: 'CLUB_AMSTORIA_IMG_6734.jpg',
          width: 1920,
          height: 1259,
        },
        {
          id: '17',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/CLUB AMSTORIA/CLUB_AMSTORIA_IMG_6737.jpg',
          altText: 'CLUB_AMSTORIA_IMG_6737.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '18',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/CLUB AMSTORIA/CLUB_AMSTORIA_IMG_6741.jpg',
          altText: 'CLUB_AMSTORIA_IMG_6741.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '19',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/CLUB AMSTORIA/CLUB_AMSTORIA_IMG_6756.jpg',
          altText: 'CLUB_AMSTORIA_IMG_6756.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '20',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/CLUB AMSTORIA/CLUB_AMSTORIA_IMG_6758.jpg',
          altText: 'CLUB_AMSTORIA_IMG_6758.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '21',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/CLUB AMSTORIA/CLUB_AMSTORIA_IMG_6760.jpg',
          altText: 'CLUB_AMSTORIA_IMG_6760.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '22',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/CLUB AMSTORIA/CLUB_AMSTORIA_IMG_6765.jpg',
          altText: 'CLUB_AMSTORIA_IMG_6765.jpg',
          width: 1280,
          height: 1920,
        },
      ],
      previous: { collectionId: '16', title: 'VILLA MARIA' },
      next: { collectionId: '1', title: 'DEANNE\u0027S HOUSE' },
      collectionId: '0',
      title: 'Club Amstoria',
    },
    {
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/DEANNE\u0027S HOUSE/DEANNE\u0027S_HOUSE_COVER.jpg',
      thumbnailAltText: 'DEANNE\u0027S_HOUSE_COVER.jpg',
      description: '',
      eager: false,
      width: 1280,
      height: 1920,
      photos: [
        {
          id: '0',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/DEANNE\u0027S HOUSE/DEANNE\u0027S_HOUSE_01-04-20238353.jpg',
          altText: 'DEANNE\u0027S_HOUSE_01-04-20238353.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '1',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/DEANNE\u0027S HOUSE/DEANNE\u0027S_HOUSE_01-04-20238355.jpg',
          altText: 'DEANNE\u0027S_HOUSE_01-04-20238355.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '2',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/DEANNE\u0027S HOUSE/DEANNE\u0027S_HOUSE_01-04-20238364.jpg',
          altText: 'DEANNE\u0027S_HOUSE_01-04-20238364.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '3',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/DEANNE\u0027S HOUSE/DEANNE\u0027S_HOUSE_01-04-20238371 1.jpg',
          altText: 'DEANNE\u0027S_HOUSE_01-04-20238371 1.jpg',
          width: 1280,
          height: 853,
        },
        {
          id: '4',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/DEANNE\u0027S HOUSE/DEANNE\u0027S_HOUSE_01-04-20238371.jpg',
          altText: 'DEANNE\u0027S_HOUSE_01-04-20238371.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '5',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/DEANNE\u0027S HOUSE/DEANNE\u0027S_HOUSE_1Q0A0138.jpg',
          altText: 'DEANNE\u0027S_HOUSE_1Q0A0138.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '6',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/DEANNE\u0027S HOUSE/DEANNE\u0027S_HOUSE_1Q0A0149.jpg',
          altText: 'DEANNE\u0027S_HOUSE_1Q0A0149.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '7',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/DEANNE\u0027S HOUSE/DEANNE\u0027S_HOUSE_1Q0A0166.jpg',
          altText: 'DEANNE\u0027S_HOUSE_1Q0A0166.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '8',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/DEANNE\u0027S HOUSE/DEANNE\u0027S_HOUSE_1Q0A1047.jpg',
          altText: 'DEANNE\u0027S_HOUSE_1Q0A1047.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '9',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/DEANNE\u0027S HOUSE/DEANNE\u0027S_HOUSE_1Q0A1157.jpg',
          altText: 'DEANNE\u0027S_HOUSE_1Q0A1157.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '10',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/DEANNE\u0027S HOUSE/DEANNE\u0027S_HOUSE_1Q0A1167.jpg',
          altText: 'DEANNE\u0027S_HOUSE_1Q0A1167.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '11',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/DEANNE\u0027S HOUSE/DEANNE\u0027S_HOUSE_COVER.jpg',
          altText: 'DEANNE\u0027S_HOUSE_COVER.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '12',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/DEANNE\u0027S HOUSE/DEANNE\u0027S_HOUSE_DEANNE_S House 27-04-230093.jpg',
          altText: 'DEANNE\u0027S_HOUSE_DEANNE_S House 27-04-230093.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '13',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/DEANNE\u0027S HOUSE/DEANNE\u0027S_HOUSE_DEANNE_S House 27-04-230113.jpg',
          altText: 'DEANNE\u0027S_HOUSE_DEANNE_S House 27-04-230113.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '14',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/DEANNE\u0027S HOUSE/DEANNE\u0027S_HOUSE_DEANNE_S House 27-04-230124.jpg',
          altText: 'DEANNE\u0027S_HOUSE_DEANNE_S House 27-04-230124.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '15',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/DEANNE\u0027S HOUSE/DEANNE\u0027S_HOUSE_DEANNE_S House 27-04-230133.jpg',
          altText: 'DEANNE\u0027S_HOUSE_DEANNE_S House 27-04-230133.jpg',
          width: 1280,
          height: 1920,
        },
      ],
      previous: { collectionId: '0', title: 'CLUB AMSTORIA' },
      next: { collectionId: '2', title: 'MOIRA' },
      collectionId: '1',
      title: 'Deanne\u0027s House',
    },
    {
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/MOIRA__GOA/MOIRA_COVER.jpg',
      thumbnailAltText: 'MOIRA_COVER.jpg',
      description: 'Goa',
      eager: false,
      width: 1280,
      height: 853,
      photos: [
        {
          id: '0',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/MOIRA__GOA/MOIRA_1Q0A1631.jpg',
          altText: 'MOIRA_1Q0A1631.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '1',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/MOIRA__GOA/MOIRA_1Q0A1643.jpg',
          altText: 'MOIRA_1Q0A1643.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '2',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/MOIRA__GOA/MOIRA_1Q0A1645.jpg',
          altText: 'MOIRA_1Q0A1645.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '3',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/MOIRA__GOA/MOIRA_1Q0A1649.jpg',
          altText: 'MOIRA_1Q0A1649.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '4',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/MOIRA__GOA/MOIRA_1Q0A1653.jpg',
          altText: 'MOIRA_1Q0A1653.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '5',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/MOIRA__GOA/MOIRA_1Q0A1724.jpg',
          altText: 'MOIRA_1Q0A1724.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '6',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/MOIRA__GOA/MOIRA_1Q0A1752.jpg',
          altText: 'MOIRA_1Q0A1752.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '7',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/MOIRA__GOA/MOIRA_1Q0A1778.jpg',
          altText: 'MOIRA_1Q0A1778.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '8',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/MOIRA__GOA/MOIRA_1Q0A1788.jpg',
          altText: 'MOIRA_1Q0A1788.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '9',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/MOIRA__GOA/MOIRA_1Q0A1808.jpg',
          altText: 'MOIRA_1Q0A1808.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '10',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/MOIRA__GOA/MOIRA_COVER.jpg',
          altText: 'MOIRA_COVER.jpg',
          width: 1280,
          height: 853,
        },
        {
          id: '11',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/MOIRA__GOA/MOIRA_MOIRA GOA0071.jpg',
          altText: 'MOIRA_MOIRA GOA0071.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '12',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/MOIRA__GOA/MOIRA_MOIRA GOA0093.jpg',
          altText: 'MOIRA_MOIRA GOA0093.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '13',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/MOIRA__GOA/MOIRA_MOIRA GOA0106.jpg',
          altText: 'MOIRA_MOIRA GOA0106.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '14',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/MOIRA__GOA/MOIRA_MOIRA GOA0112.jpg',
          altText: 'MOIRA_MOIRA GOA0112.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '15',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/MOIRA__GOA/MOIRA_MOIRA GOA0123.jpg',
          altText: 'MOIRA_MOIRA GOA0123.jpg',
          width: 1280,
          height: 853,
        },
        {
          id: '16',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/MOIRA__GOA/MOIRA_MOIRA GOA0159.jpg',
          altText: 'MOIRA_MOIRA GOA0159.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '17',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/MOIRA__GOA/MOIRA_MOIRA GOA0167.jpg',
          altText: 'MOIRA_MOIRA GOA0167.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '18',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/MOIRA__GOA/MOIRA_MOIRA GOA0177.jpg',
          altText: 'MOIRA_MOIRA GOA0177.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '19',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/MOIRA__GOA/MOIRA_MOIRA GOA0183.jpg',
          altText: 'MOIRA_MOIRA GOA0183.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '20',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/MOIRA__GOA/MOIRA_MOIRA GOA0192.jpg',
          altText: 'MOIRA_MOIRA GOA0192.jpg',
          width: 1280,
          height: 1920,
        },
      ],
      previous: { collectionId: '1', title: 'DEANNE\u0027S HOUSE' },
      next: { collectionId: '3', title: 'RED BLUE YELLOW MUMBAI' },
      collectionId: '2',
      title: 'Moira',
    },
    {
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RED BLUE YELLOW MUMBAI/RED_BLUE_YELLOW_MUMBAI_COVER.jpg',
      thumbnailAltText: 'RED_BLUE_YELLOW_MUMBAI_COVER.jpg',
      description: '',
      eager: false,
      width: 1280,
      height: 1920,
      photos: [
        {
          id: '0',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RED BLUE YELLOW MUMBAI/RED_BLUE_YELLOW_MUMBAI_1Q0A1904.jpg',
          altText: 'RED_BLUE_YELLOW_MUMBAI_1Q0A1904.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '1',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RED BLUE YELLOW MUMBAI/RED_BLUE_YELLOW_MUMBAI_1Q0A1915.jpg',
          altText: 'RED_BLUE_YELLOW_MUMBAI_1Q0A1915.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '2',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RED BLUE YELLOW MUMBAI/RED_BLUE_YELLOW_MUMBAI_1Q0A1923.jpg',
          altText: 'RED_BLUE_YELLOW_MUMBAI_1Q0A1923.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '3',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RED BLUE YELLOW MUMBAI/RED_BLUE_YELLOW_MUMBAI_1Q0A1932.jpg',
          altText: 'RED_BLUE_YELLOW_MUMBAI_1Q0A1932.jpg',
          width: 1686,
          height: 1280,
        },
        {
          id: '4',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RED BLUE YELLOW MUMBAI/RED_BLUE_YELLOW_MUMBAI_1Q0A1940.jpg',
          altText: 'RED_BLUE_YELLOW_MUMBAI_1Q0A1940.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '5',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RED BLUE YELLOW MUMBAI/RED_BLUE_YELLOW_MUMBAI_COVER.jpg',
          altText: 'RED_BLUE_YELLOW_MUMBAI_COVER.jpg',
          width: 1280,
          height: 1920,
        },
      ],
      previous: { collectionId: '2', title: 'MOIRA' },
      next: { collectionId: '4', title: 'RED BLUE YELLOW, MUMBAI' },
      collectionId: '3',
      title: 'Red Blue Yellow Mumbai',
    },
    {
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RED BLUE YELLOW, MUMBAI__ARANYA/RED_BLUE_YELLOW,_MUMBAI_COVER.jpg',
      thumbnailAltText: 'RED_BLUE_YELLOW,_MUMBAI_COVER.jpg',
      description: 'Aranya',
      eager: false,
      width: 1920,
      height: 1280,
      photos: [
        {
          id: '0',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RED BLUE YELLOW, MUMBAI__ARANYA/RED_BLUE_YELLOW,_MUMBAI_1Q0A9875.jpg',
          altText: 'RED_BLUE_YELLOW,_MUMBAI_1Q0A9875.jpg',
          width: 1920,
          height: 1266,
        },
        {
          id: '1',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RED BLUE YELLOW, MUMBAI__ARANYA/RED_BLUE_YELLOW,_MUMBAI_1Q0A9877.jpg',
          altText: 'RED_BLUE_YELLOW,_MUMBAI_1Q0A9877.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '2',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RED BLUE YELLOW, MUMBAI__ARANYA/RED_BLUE_YELLOW,_MUMBAI_1Q0A9890.jpg',
          altText: 'RED_BLUE_YELLOW,_MUMBAI_1Q0A9890.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '3',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RED BLUE YELLOW, MUMBAI__ARANYA/RED_BLUE_YELLOW,_MUMBAI_1Q0A9895.jpg',
          altText: 'RED_BLUE_YELLOW,_MUMBAI_1Q0A9895.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '4',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RED BLUE YELLOW, MUMBAI__ARANYA/RED_BLUE_YELLOW,_MUMBAI_1Q0A9899.jpg',
          altText: 'RED_BLUE_YELLOW,_MUMBAI_1Q0A9899.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '5',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RED BLUE YELLOW, MUMBAI__ARANYA/RED_BLUE_YELLOW,_MUMBAI_1Q0A9900.jpg',
          altText: 'RED_BLUE_YELLOW,_MUMBAI_1Q0A9900.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '6',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RED BLUE YELLOW, MUMBAI__ARANYA/RED_BLUE_YELLOW,_MUMBAI_1Q0A9906.jpg',
          altText: 'RED_BLUE_YELLOW,_MUMBAI_1Q0A9906.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '7',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RED BLUE YELLOW, MUMBAI__ARANYA/RED_BLUE_YELLOW,_MUMBAI_1Q0A9907.jpg',
          altText: 'RED_BLUE_YELLOW,_MUMBAI_1Q0A9907.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '8',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RED BLUE YELLOW, MUMBAI__ARANYA/RED_BLUE_YELLOW,_MUMBAI_1Q0A9909.jpg',
          altText: 'RED_BLUE_YELLOW,_MUMBAI_1Q0A9909.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '9',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RED BLUE YELLOW, MUMBAI__ARANYA/RED_BLUE_YELLOW,_MUMBAI_1Q0A9910.jpg',
          altText: 'RED_BLUE_YELLOW,_MUMBAI_1Q0A9910.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '10',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RED BLUE YELLOW, MUMBAI__ARANYA/RED_BLUE_YELLOW,_MUMBAI_1Q0A9913.jpg',
          altText: 'RED_BLUE_YELLOW,_MUMBAI_1Q0A9913.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '11',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RED BLUE YELLOW, MUMBAI__ARANYA/RED_BLUE_YELLOW,_MUMBAI_1Q0A9920.jpg',
          altText: 'RED_BLUE_YELLOW,_MUMBAI_1Q0A9920.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '12',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RED BLUE YELLOW, MUMBAI__ARANYA/RED_BLUE_YELLOW,_MUMBAI_1Q0A9923.jpg',
          altText: 'RED_BLUE_YELLOW,_MUMBAI_1Q0A9923.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '13',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RED BLUE YELLOW, MUMBAI__ARANYA/RED_BLUE_YELLOW,_MUMBAI_1Q0A9931.jpg',
          altText: 'RED_BLUE_YELLOW,_MUMBAI_1Q0A9931.jpg',
          width: 1266,
          height: 1920,
        },
        {
          id: '14',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RED BLUE YELLOW, MUMBAI__ARANYA/RED_BLUE_YELLOW,_MUMBAI_1Q0A9934.jpg',
          altText: 'RED_BLUE_YELLOW,_MUMBAI_1Q0A9934.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '15',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RED BLUE YELLOW, MUMBAI__ARANYA/RED_BLUE_YELLOW,_MUMBAI_1Q0A9935.jpg',
          altText: 'RED_BLUE_YELLOW,_MUMBAI_1Q0A9935.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '16',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RED BLUE YELLOW, MUMBAI__ARANYA/RED_BLUE_YELLOW,_MUMBAI_1Q0A9937.jpg',
          altText: 'RED_BLUE_YELLOW,_MUMBAI_1Q0A9937.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '17',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RED BLUE YELLOW, MUMBAI__ARANYA/RED_BLUE_YELLOW,_MUMBAI_COVER.jpg',
          altText: 'RED_BLUE_YELLOW,_MUMBAI_COVER.jpg',
          width: 1920,
          height: 1280,
        },
      ],
      previous: { collectionId: '3', title: 'RED BLUE YELLOW MUMBAI' },
      next: { collectionId: '5', title: 'RITAKSHI ARORA DESIGNS' },
      collectionId: '4',
      title: 'Red Blue Yellow, Mumbai',
    },
    {
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RITAKSHI ARORA DESIGNS__HOME/RITAKSHI_ARORA_DESIGNS_COVER.jpg',
      thumbnailAltText: 'RITAKSHI_ARORA_DESIGNS_COVER.jpg',
      description: 'Home',
      eager: false,
      width: 1620,
      height: 1080,
      photos: [
        {
          id: '0',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RITAKSHI ARORA DESIGNS__HOME/RITAKSHI_ARORA_DESIGNS_COVER.jpg',
          altText: 'RITAKSHI_ARORA_DESIGNS_COVER.jpg',
          width: 1620,
          height: 1080,
        },
        {
          id: '1',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RITAKSHI ARORA DESIGNS__HOME/RITAKSHI_ARORA_DESIGNS_IMG_6318.jpg',
          altText: 'RITAKSHI_ARORA_DESIGNS_IMG_6318.jpg',
          width: 1642,
          height: 1080,
        },
        {
          id: '2',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RITAKSHI ARORA DESIGNS__HOME/RITAKSHI_ARORA_DESIGNS_IMG_6348.jpg',
          altText: 'RITAKSHI_ARORA_DESIGNS_IMG_6348.jpg',
          width: 1256,
          height: 1920,
        },
        {
          id: '3',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RITAKSHI ARORA DESIGNS__HOME/RITAKSHI_ARORA_DESIGNS_IMG_6350.jpg',
          altText: 'RITAKSHI_ARORA_DESIGNS_IMG_6350.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '4',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RITAKSHI ARORA DESIGNS__HOME/RITAKSHI_ARORA_DESIGNS_IMG_6362.jpg',
          altText: 'RITAKSHI_ARORA_DESIGNS_IMG_6362.jpg',
          width: 1636,
          height: 1080,
        },
        {
          id: '5',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RITAKSHI ARORA DESIGNS__HOME/RITAKSHI_ARORA_DESIGNS_IMG_6379.jpg',
          altText: 'RITAKSHI_ARORA_DESIGNS_IMG_6379.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '6',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RITAKSHI ARORA DESIGNS__HOME/RITAKSHI_ARORA_DESIGNS_IMG_6380.jpg',
          altText: 'RITAKSHI_ARORA_DESIGNS_IMG_6380.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '7',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RITAKSHI ARORA DESIGNS__HOME/RITAKSHI_ARORA_DESIGNS_IMG_6386.jpg',
          altText: 'RITAKSHI_ARORA_DESIGNS_IMG_6386.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '8',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RITAKSHI ARORA DESIGNS__HOME/RITAKSHI_ARORA_DESIGNS_IMG_6389.jpg',
          altText: 'RITAKSHI_ARORA_DESIGNS_IMG_6389.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '9',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RITAKSHI ARORA DESIGNS__HOME/RITAKSHI_ARORA_DESIGNS_IMG_6391.jpg',
          altText: 'RITAKSHI_ARORA_DESIGNS_IMG_6391.jpg',
          width: 1641,
          height: 1080,
        },
        {
          id: '10',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RITAKSHI ARORA DESIGNS__HOME/RITAKSHI_ARORA_DESIGNS_IMG_6411.jpg',
          altText: 'RITAKSHI_ARORA_DESIGNS_IMG_6411.jpg',
          width: 1641,
          height: 1080,
        },
        {
          id: '11',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RITAKSHI ARORA DESIGNS__HOME/RITAKSHI_ARORA_DESIGNS_IMG_6419.jpg',
          altText: 'RITAKSHI_ARORA_DESIGNS_IMG_6419.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '12',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RITAKSHI ARORA DESIGNS__HOME/RITAKSHI_ARORA_DESIGNS_IMG_6428.jpg',
          altText: 'RITAKSHI_ARORA_DESIGNS_IMG_6428.jpg',
          width: 1641,
          height: 1080,
        },
        {
          id: '13',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RITAKSHI ARORA DESIGNS__HOME/RITAKSHI_ARORA_DESIGNS_IMG_6437.jpg',
          altText: 'RITAKSHI_ARORA_DESIGNS_IMG_6437.jpg',
          width: 1641,
          height: 1080,
        },
        {
          id: '14',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RITAKSHI ARORA DESIGNS__HOME/RITAKSHI_ARORA_DESIGNS_IMG_6485.jpg',
          altText: 'RITAKSHI_ARORA_DESIGNS_IMG_6485.jpg',
          width: 1641,
          height: 1080,
        },
      ],
      previous: { collectionId: '4', title: 'RED BLUE YELLOW, MUMBAI' },
      next: { collectionId: '6', title: 'RITAKSHI ARORA DESIGNS' },
      collectionId: '5',
      title: 'Ritakshi Arora Designs',
    },
    {
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RITAKSHI ARORA DESIGNS__OFFICE/RITAKSHI_ARORA_DESIGNS_COVER.jpg',
      thumbnailAltText: 'RITAKSHI_ARORA_DESIGNS_COVER.jpg',
      description: 'Office',
      eager: false,
      width: 1920,
      height: 1263,
      photos: [
        {
          id: '0',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RITAKSHI ARORA DESIGNS__OFFICE/RITAKSHI_ARORA_DESIGNS_COVER.jpg',
          altText: 'RITAKSHI_ARORA_DESIGNS_COVER.jpg',
          width: 1920,
          height: 1263,
        },
        {
          id: '1',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RITAKSHI ARORA DESIGNS__OFFICE/RITAKSHI_ARORA_DESIGNS_IMG_6504.jpg',
          altText: 'RITAKSHI_ARORA_DESIGNS_IMG_6504.jpg',
          width: 1920,
          height: 1263,
        },
        {
          id: '2',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RITAKSHI ARORA DESIGNS__OFFICE/RITAKSHI_ARORA_DESIGNS_IMG_6509.jpg',
          altText: 'RITAKSHI_ARORA_DESIGNS_IMG_6509.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '3',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RITAKSHI ARORA DESIGNS__OFFICE/RITAKSHI_ARORA_DESIGNS_IMG_6514.jpg',
          altText: 'RITAKSHI_ARORA_DESIGNS_IMG_6514.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '4',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RITAKSHI ARORA DESIGNS__OFFICE/RITAKSHI_ARORA_DESIGNS_IMG_6593.jpg',
          altText: 'RITAKSHI_ARORA_DESIGNS_IMG_6593.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '5',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RITAKSHI ARORA DESIGNS__OFFICE/RITAKSHI_ARORA_DESIGNS_IMG_6605.jpg',
          altText: 'RITAKSHI_ARORA_DESIGNS_IMG_6605.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '6',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RITAKSHI ARORA DESIGNS__OFFICE/RITAKSHI_ARORA_DESIGNS_IMG_6606.jpg',
          altText: 'RITAKSHI_ARORA_DESIGNS_IMG_6606.jpg',
          width: 1920,
          height: 1263,
        },
      ],
      previous: { collectionId: '5', title: 'RITAKSHI ARORA DESIGNS' },
      next: { collectionId: '7', title: 'RIVERDALE' },
      collectionId: '6',
      title: 'Ritakshi Arora Designs',
    },
    {
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RIVERDALE__The Accent Bay Design Studio/RIVERDALE_COVER.jpg',
      thumbnailAltText: 'RIVERDALE_COVER.jpg',
      description: 'The Accent Bay Design Studio',
      eager: false,
      width: 1920,
      height: 1280,
      photos: [
        {
          id: '0',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RIVERDALE__The Accent Bay Design Studio/RIVERDALE_COVER.jpg',
          altText: 'RIVERDALE_COVER.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '1',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RIVERDALE__The Accent Bay Design Studio/RIVERDALE_IMG_6155.jpg',
          altText: 'RIVERDALE_IMG_6155.jpg',
          width: 1920,
          height: 1271,
        },
        {
          id: '2',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RIVERDALE__The Accent Bay Design Studio/RIVERDALE_IMG_6162.jpg',
          altText: 'RIVERDALE_IMG_6162.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '3',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RIVERDALE__The Accent Bay Design Studio/RIVERDALE_IMG_6164.jpg',
          altText: 'RIVERDALE_IMG_6164.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '4',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RIVERDALE__The Accent Bay Design Studio/RIVERDALE_IMG_6177.jpg',
          altText: 'RIVERDALE_IMG_6177.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '5',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RIVERDALE__The Accent Bay Design Studio/RIVERDALE_IMG_6179.jpg',
          altText: 'RIVERDALE_IMG_6179.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '6',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RIVERDALE__The Accent Bay Design Studio/RIVERDALE_IMG_6181.jpg',
          altText: 'RIVERDALE_IMG_6181.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '7',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RIVERDALE__The Accent Bay Design Studio/RIVERDALE_IMG_6192.jpg',
          altText: 'RIVERDALE_IMG_6192.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '8',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RIVERDALE__The Accent Bay Design Studio/RIVERDALE_IMG_6195.jpg',
          altText: 'RIVERDALE_IMG_6195.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '9',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/RIVERDALE__The Accent Bay Design Studio/RIVERDALE_IMG_6198.jpg',
          altText: 'RIVERDALE_IMG_6198.jpg',
          width: 1280,
          height: 1920,
        },
      ],
      previous: { collectionId: '6', title: 'RITAKSHI ARORA DESIGNS' },
      next: { collectionId: '8', title: 'SHONA NATH' },
      collectionId: '7',
      title: 'Riverdale',
    },
    {
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/SHONA NATH/SHONA_NATH_COVER.jpg',
      thumbnailAltText: 'SHONA_NATH_COVER.jpg',
      description: '',
      eager: false,
      width: 1280,
      height: 1920,
      photos: [
        {
          id: '0',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/SHONA NATH/SHONA_NATH_COVER.jpg',
          altText: 'SHONA_NATH_COVER.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '1',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/SHONA NATH/SHONA_NATH_IMG_6835.jpg',
          altText: 'SHONA_NATH_IMG_6835.jpg',
          width: 1920,
          height: 1263,
        },
        {
          id: '2',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/SHONA NATH/SHONA_NATH_IMG_6856.jpg',
          altText: 'SHONA_NATH_IMG_6856.jpg',
          width: 1920,
          height: 1263,
        },
        {
          id: '3',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/SHONA NATH/SHONA_NATH_IMG_6865.jpg',
          altText: 'SHONA_NATH_IMG_6865.jpg',
          width: 1280,
          height: 1920,
        },
      ],
      previous: { collectionId: '7', title: 'RIVERDALE' },
      next: { collectionId: '9', title: 'Studio Mares Design' },
      collectionId: '8',
      title: 'Shona Nath',
    },
    {
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/Studio Mares Design/Studio_Mares_Design_COVER.jpg',
      thumbnailAltText: 'Studio_Mares_Design_COVER.jpg',
      description: '',
      eager: false,
      width: 1280,
      height: 1920,
      photos: [
        {
          id: '0',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/Studio Mares Design/Studio_Mares_Design_0S8A7391.jpg',
          altText: 'Studio_Mares_Design_0S8A7391.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '1',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/Studio Mares Design/Studio_Mares_Design_0S8A7392.jpg',
          altText: 'Studio_Mares_Design_0S8A7392.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '2',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/Studio Mares Design/Studio_Mares_Design_0S8A7394.jpg',
          altText: 'Studio_Mares_Design_0S8A7394.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '3',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/Studio Mares Design/Studio_Mares_Design_0S8A7403.jpg',
          altText: 'Studio_Mares_Design_0S8A7403.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '4',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/Studio Mares Design/Studio_Mares_Design_0S8A7408.jpg',
          altText: 'Studio_Mares_Design_0S8A7408.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '5',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/Studio Mares Design/Studio_Mares_Design_0S8A7410.jpg',
          altText: 'Studio_Mares_Design_0S8A7410.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '6',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/Studio Mares Design/Studio_Mares_Design_0S8A7419.jpg',
          altText: 'Studio_Mares_Design_0S8A7419.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '7',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/Studio Mares Design/Studio_Mares_Design_0S8A7421.jpg',
          altText: 'Studio_Mares_Design_0S8A7421.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '8',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/Studio Mares Design/Studio_Mares_Design_0S8A7422.jpg',
          altText: 'Studio_Mares_Design_0S8A7422.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '9',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/Studio Mares Design/Studio_Mares_Design_0S8A7441.jpg',
          altText: 'Studio_Mares_Design_0S8A7441.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '10',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/Studio Mares Design/Studio_Mares_Design_0S8A7442.jpg',
          altText: 'Studio_Mares_Design_0S8A7442.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '11',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/Studio Mares Design/Studio_Mares_Design_0S8A7444.jpg',
          altText: 'Studio_Mares_Design_0S8A7444.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '12',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/Studio Mares Design/Studio_Mares_Design_0S8A7447.jpg',
          altText: 'Studio_Mares_Design_0S8A7447.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '13',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/Studio Mares Design/Studio_Mares_Design_0S8A7452.jpg',
          altText: 'Studio_Mares_Design_0S8A7452.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '14',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/Studio Mares Design/Studio_Mares_Design_0S8A7464.jpg',
          altText: 'Studio_Mares_Design_0S8A7464.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '15',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/Studio Mares Design/Studio_Mares_Design_0S8A7469.jpg',
          altText: 'Studio_Mares_Design_0S8A7469.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '16',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/Studio Mares Design/Studio_Mares_Design_0S8A7472.jpg',
          altText: 'Studio_Mares_Design_0S8A7472.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '17',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/Studio Mares Design/Studio_Mares_Design_0S8A7474.jpg',
          altText: 'Studio_Mares_Design_0S8A7474.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '18',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/Studio Mares Design/Studio_Mares_Design_0S8A7481.jpg',
          altText: 'Studio_Mares_Design_0S8A7481.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '19',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/Studio Mares Design/Studio_Mares_Design_0S8A7484.jpg',
          altText: 'Studio_Mares_Design_0S8A7484.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '20',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/Studio Mares Design/Studio_Mares_Design_0S8A7510.jpg',
          altText: 'Studio_Mares_Design_0S8A7510.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '21',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/Studio Mares Design/Studio_Mares_Design_0S8A7513.jpg',
          altText: 'Studio_Mares_Design_0S8A7513.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '22',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/Studio Mares Design/Studio_Mares_Design_COVER.jpg',
          altText: 'Studio_Mares_Design_COVER.jpg',
          width: 1280,
          height: 1920,
        },
      ],
      previous: { collectionId: '8', title: 'SHONA NATH' },
      next: { collectionId: '10', title: 'TANUJA \u0026 ASSOCIATES' },
      collectionId: '9',
      title: 'Studio Mares Design',
    },
    {
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/TANUJA \u0026 ASSOCIATES/TANUJA_\u0026_ASSOCIATES_COVER.jpg',
      thumbnailAltText: 'TANUJA_\u0026_ASSOCIATES_COVER.jpg',
      description: '',
      eager: false,
      width: 1280,
      height: 1920,
      photos: [
        {
          id: '0',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/TANUJA \u0026 ASSOCIATES/TANUJA_\u0026_ASSOCIATES_COVER.jpg',
          altText: 'TANUJA_\u0026_ASSOCIATES_COVER.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '1',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/TANUJA \u0026 ASSOCIATES/TANUJA_\u0026_ASSOCIATES_IMG_0250.jpg',
          altText: 'TANUJA_\u0026_ASSOCIATES_IMG_0250.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '2',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/TANUJA \u0026 ASSOCIATES/TANUJA_\u0026_ASSOCIATES_IMG_0262.jpg',
          altText: 'TANUJA_\u0026_ASSOCIATES_IMG_0262.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '3',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/TANUJA \u0026 ASSOCIATES/TANUJA_\u0026_ASSOCIATES_IMG_0289.jpg',
          altText: 'TANUJA_\u0026_ASSOCIATES_IMG_0289.jpg',
          width: 1280,
          height: 1920,
        },
      ],
      previous: { collectionId: '9', title: 'Studio Mares Design' },
      next: { collectionId: '11', title: 'The Accent Bay Design Studio' },
      collectionId: '10',
      title: 'Tanuja \u0026 Associates',
    },
    {
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Accent Bay Design Studio__Kanjurmarg house/The_Accent_Bay_Design_Studio_COVER.jpg',
      thumbnailAltText: 'The_Accent_Bay_Design_Studio_COVER.jpg',
      description: 'Kanjurmarg House',
      eager: false,
      width: 1920,
      height: 1280,
      photos: [
        {
          id: '0',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Accent Bay Design Studio__Kanjurmarg house/The_Accent_Bay_Design_Studio_0S8A7452.jpg',
          altText: 'The_Accent_Bay_Design_Studio_0S8A7452.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '1',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Accent Bay Design Studio__Kanjurmarg house/The_Accent_Bay_Design_Studio_0S8A7464.jpg',
          altText: 'The_Accent_Bay_Design_Studio_0S8A7464.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '2',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Accent Bay Design Studio__Kanjurmarg house/The_Accent_Bay_Design_Studio_0S8A7481.jpg',
          altText: 'The_Accent_Bay_Design_Studio_0S8A7481.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '3',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Accent Bay Design Studio__Kanjurmarg house/The_Accent_Bay_Design_Studio_0S8A7489.jpg',
          altText: 'The_Accent_Bay_Design_Studio_0S8A7489.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '4',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Accent Bay Design Studio__Kanjurmarg house/The_Accent_Bay_Design_Studio_0S8A7503.jpg',
          altText: 'The_Accent_Bay_Design_Studio_0S8A7503.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '5',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Accent Bay Design Studio__Kanjurmarg house/The_Accent_Bay_Design_Studio_0S8A7509.jpg',
          altText: 'The_Accent_Bay_Design_Studio_0S8A7509.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '6',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Accent Bay Design Studio__Kanjurmarg house/The_Accent_Bay_Design_Studio_0S8A7514.jpg',
          altText: 'The_Accent_Bay_Design_Studio_0S8A7514.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '7',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Accent Bay Design Studio__Kanjurmarg house/The_Accent_Bay_Design_Studio_0S8A7517.jpg',
          altText: 'The_Accent_Bay_Design_Studio_0S8A7517.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '8',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Accent Bay Design Studio__Kanjurmarg house/The_Accent_Bay_Design_Studio_0S8A7519.jpg',
          altText: 'The_Accent_Bay_Design_Studio_0S8A7519.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '9',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Accent Bay Design Studio__Kanjurmarg house/The_Accent_Bay_Design_Studio_0S8A7523.jpg',
          altText: 'The_Accent_Bay_Design_Studio_0S8A7523.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '10',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Accent Bay Design Studio__Kanjurmarg house/The_Accent_Bay_Design_Studio_0S8A7524.jpg',
          altText: 'The_Accent_Bay_Design_Studio_0S8A7524.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '11',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Accent Bay Design Studio__Kanjurmarg house/The_Accent_Bay_Design_Studio_COVER.jpg',
          altText: 'The_Accent_Bay_Design_Studio_COVER.jpg',
          width: 1920,
          height: 1280,
        },
      ],
      previous: { collectionId: '10', title: 'TANUJA \u0026 ASSOCIATES' },
      next: { collectionId: '12', title: 'THE COASTAL VILLA' },
      collectionId: '11',
      title: 'The Accent Bay Design Studio',
    },
    {
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/THE COASTAL VILLA__DAPOLI/THE_COASTAL_VILLA_COVER.jpg',
      thumbnailAltText: 'THE_COASTAL_VILLA_COVER.jpg',
      description: 'Dapoli',
      eager: false,
      width: 1920,
      height: 1280,
      photos: [
        {
          id: '0',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/THE COASTAL VILLA__DAPOLI/THE_COASTAL_VILLA_COVER.jpg',
          altText: 'THE_COASTAL_VILLA_COVER.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '1',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/THE COASTAL VILLA__DAPOLI/THE_COASTAL_VILLA_IMG_4345.jpg',
          altText: 'THE_COASTAL_VILLA_IMG_4345.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '2',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/THE COASTAL VILLA__DAPOLI/THE_COASTAL_VILLA_IMG_4366.jpg',
          altText: 'THE_COASTAL_VILLA_IMG_4366.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '3',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/THE COASTAL VILLA__DAPOLI/THE_COASTAL_VILLA_IMG_4410.jpg',
          altText: 'THE_COASTAL_VILLA_IMG_4410.jpg',
          width: 1278,
          height: 1920,
        },
        {
          id: '4',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/THE COASTAL VILLA__DAPOLI/THE_COASTAL_VILLA_IMG_4488.jpg',
          altText: 'THE_COASTAL_VILLA_IMG_4488.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '5',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/THE COASTAL VILLA__DAPOLI/THE_COASTAL_VILLA_IMG_4508.jpg',
          altText: 'THE_COASTAL_VILLA_IMG_4508.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '6',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/THE COASTAL VILLA__DAPOLI/THE_COASTAL_VILLA_IMG_4521.jpg',
          altText: 'THE_COASTAL_VILLA_IMG_4521.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '7',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/THE COASTAL VILLA__DAPOLI/THE_COASTAL_VILLA_IMG_4531.jpg',
          altText: 'THE_COASTAL_VILLA_IMG_4531.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '8',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/THE COASTAL VILLA__DAPOLI/THE_COASTAL_VILLA_IMG_4537.jpg',
          altText: 'THE_COASTAL_VILLA_IMG_4537.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '9',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/THE COASTAL VILLA__DAPOLI/THE_COASTAL_VILLA_IMG_4893.jpg',
          altText: 'THE_COASTAL_VILLA_IMG_4893.jpg',
          width: 1280,
          height: 1920,
        },
      ],
      previous: { collectionId: '11', title: 'The Accent Bay Design Studio' },
      next: { collectionId: '13', title: 'The Nirmiti House' },
      collectionId: '12',
      title: 'The Coastal Villa',
    },
    {
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Nirmiti House__The Accent Bay Design Studio/The_Nirmiti_House_COVER.jpg',
      thumbnailAltText: 'The_Nirmiti_House_COVER.jpg',
      description: 'The Accent Bay Design Studio',
      eager: false,
      width: 1280,
      height: 1920,
      photos: [
        {
          id: '0',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Nirmiti House__The Accent Bay Design Studio/The_Nirmiti_House_COVER.jpg',
          altText: 'The_Nirmiti_House_COVER.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '1',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Nirmiti House__The Accent Bay Design Studio/The_Nirmiti_House_DSC00003.jpg',
          altText: 'The_Nirmiti_House_DSC00003.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '2',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Nirmiti House__The Accent Bay Design Studio/The_Nirmiti_House_DSC00008.jpg',
          altText: 'The_Nirmiti_House_DSC00008.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '3',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Nirmiti House__The Accent Bay Design Studio/The_Nirmiti_House_DSC00016.jpg',
          altText: 'The_Nirmiti_House_DSC00016.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '4',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Nirmiti House__The Accent Bay Design Studio/The_Nirmiti_House_DSC00018.jpg',
          altText: 'The_Nirmiti_House_DSC00018.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '5',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Nirmiti House__The Accent Bay Design Studio/The_Nirmiti_House_DSC00027.jpg',
          altText: 'The_Nirmiti_House_DSC00027.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '6',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Nirmiti House__The Accent Bay Design Studio/The_Nirmiti_House_DSC00511.jpg',
          altText: 'The_Nirmiti_House_DSC00511.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '7',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Nirmiti House__The Accent Bay Design Studio/The_Nirmiti_House_DSC00524.jpg',
          altText: 'The_Nirmiti_House_DSC00524.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '8',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Nirmiti House__The Accent Bay Design Studio/The_Nirmiti_House_DSC00527.jpg',
          altText: 'The_Nirmiti_House_DSC00527.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '9',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Nirmiti House__The Accent Bay Design Studio/The_Nirmiti_House_DSC00531.jpg',
          altText: 'The_Nirmiti_House_DSC00531.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '10',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Nirmiti House__The Accent Bay Design Studio/The_Nirmiti_House_DSC00543.jpg',
          altText: 'The_Nirmiti_House_DSC00543.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '11',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Nirmiti House__The Accent Bay Design Studio/The_Nirmiti_House_DSC00569.jpg',
          altText: 'The_Nirmiti_House_DSC00569.jpg',
          width: 1280,
          height: 1920,
        },
      ],
      previous: { collectionId: '12', title: 'THE COASTAL VILLA' },
      next: { collectionId: '14', title: 'The Slide House' },
      collectionId: '13',
      title: 'The Nirmiti House',
    },
    {
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Slide House__Alibaug/The_Slide_House_COVER.jpg',
      thumbnailAltText: 'The_Slide_House_COVER.jpg',
      description: 'Alibaug',
      eager: false,
      width: 1920,
      height: 1280,
      photos: [
        {
          id: '0',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Slide House__Alibaug/The_Slide_House_4L2A4284.jpg',
          altText: 'The_Slide_House_4L2A4284.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '1',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Slide House__Alibaug/The_Slide_House_4L2A4285.jpg',
          altText: 'The_Slide_House_4L2A4285.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '2',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Slide House__Alibaug/The_Slide_House_4L2A4290.jpg',
          altText: 'The_Slide_House_4L2A4290.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '3',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Slide House__Alibaug/The_Slide_House_4L2A4292.jpg',
          altText: 'The_Slide_House_4L2A4292.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '4',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Slide House__Alibaug/The_Slide_House_4L2A4304.jpg',
          altText: 'The_Slide_House_4L2A4304.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '5',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Slide House__Alibaug/The_Slide_House_4L2A4314.jpg',
          altText: 'The_Slide_House_4L2A4314.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '6',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Slide House__Alibaug/The_Slide_House_4L2A4320.jpg',
          altText: 'The_Slide_House_4L2A4320.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '7',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Slide House__Alibaug/The_Slide_House_4L2A4329.jpg',
          altText: 'The_Slide_House_4L2A4329.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '8',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Slide House__Alibaug/The_Slide_House_4L2A4345.jpg',
          altText: 'The_Slide_House_4L2A4345.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '9',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Slide House__Alibaug/The_Slide_House_4L2A4346.jpg',
          altText: 'The_Slide_House_4L2A4346.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '10',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Slide House__Alibaug/The_Slide_House_4L2A4356.jpg',
          altText: 'The_Slide_House_4L2A4356.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '11',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Slide House__Alibaug/The_Slide_House_4L2A4359.jpg',
          altText: 'The_Slide_House_4L2A4359.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '12',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Slide House__Alibaug/The_Slide_House_4L2A4363.jpg',
          altText: 'The_Slide_House_4L2A4363.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '13',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Slide House__Alibaug/The_Slide_House_4L2A4368.jpg',
          altText: 'The_Slide_House_4L2A4368.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '14',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Slide House__Alibaug/The_Slide_House_4L2A4371.jpg',
          altText: 'The_Slide_House_4L2A4371.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '15',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/The Slide House__Alibaug/The_Slide_House_COVER.jpg',
          altText: 'The_Slide_House_COVER.jpg',
          width: 1920,
          height: 1280,
        },
      ],
      previous: { collectionId: '13', title: 'The Nirmiti House' },
      next: { collectionId: '15', title: 'THE TERRACE GARDEN' },
      collectionId: '14',
      title: 'The Slide House',
    },
    {
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/THE TERRACE GARDEN/THE_TERRACE_GARDEN_COVER.jpg',
      thumbnailAltText: 'THE_TERRACE_GARDEN_COVER.jpg',
      description: '',
      eager: false,
      width: 1920,
      height: 1280,
      photos: [
        {
          id: '0',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/THE TERRACE GARDEN/THE_TERRACE_GARDEN_1Q0A3087.jpg',
          altText: 'THE_TERRACE_GARDEN_1Q0A3087.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '1',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/THE TERRACE GARDEN/THE_TERRACE_GARDEN_1Q0A3143.jpg',
          altText: 'THE_TERRACE_GARDEN_1Q0A3143.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '2',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/THE TERRACE GARDEN/THE_TERRACE_GARDEN_1Q0A3145.jpg',
          altText: 'THE_TERRACE_GARDEN_1Q0A3145.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '3',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/THE TERRACE GARDEN/THE_TERRACE_GARDEN_1Q0A3208.jpg',
          altText: 'THE_TERRACE_GARDEN_1Q0A3208.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '4',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/THE TERRACE GARDEN/THE_TERRACE_GARDEN_1Q0A3215.jpg',
          altText: 'THE_TERRACE_GARDEN_1Q0A3215.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '5',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/THE TERRACE GARDEN/THE_TERRACE_GARDEN_1Q0A3236.jpg',
          altText: 'THE_TERRACE_GARDEN_1Q0A3236.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '6',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/THE TERRACE GARDEN/THE_TERRACE_GARDEN_1Q0A3242.jpg',
          altText: 'THE_TERRACE_GARDEN_1Q0A3242.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '7',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/THE TERRACE GARDEN/THE_TERRACE_GARDEN_1Q0A3259.jpg',
          altText: 'THE_TERRACE_GARDEN_1Q0A3259.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '8',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/THE TERRACE GARDEN/THE_TERRACE_GARDEN_COVER.jpg',
          altText: 'THE_TERRACE_GARDEN_COVER.jpg',
          width: 1920,
          height: 1280,
        },
      ],
      previous: { collectionId: '14', title: 'The Slide House' },
      next: { collectionId: '16', title: 'VILLA MARIA' },
      collectionId: '15',
      title: 'The Terrace Garden',
    },
    {
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/VILLA MARIA__Pune/VILLA_MARIA_COVER.jpg',
      thumbnailAltText: 'VILLA_MARIA_COVER.jpg',
      description: 'Pune',
      eager: false,
      width: 1920,
      height: 1280,
      photos: [
        {
          id: '0',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/VILLA MARIA__Pune/VILLA_MARIA_COVER.jpg',
          altText: 'VILLA_MARIA_COVER.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '1',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/VILLA MARIA__Pune/VILLA_MARIA_IMG_9534.jpg',
          altText: 'VILLA_MARIA_IMG_9534.jpg',
          width: 1920,
          height: 1266,
        },
        {
          id: '2',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/VILLA MARIA__Pune/VILLA_MARIA_IMG_9539.jpg',
          altText: 'VILLA_MARIA_IMG_9539.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '3',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/VILLA MARIA__Pune/VILLA_MARIA_IMG_9558.jpg',
          altText: 'VILLA_MARIA_IMG_9558.jpg',
          width: 1920,
          height: 1263,
        },
        {
          id: '4',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/VILLA MARIA__Pune/VILLA_MARIA_IMG_9564.jpg',
          altText: 'VILLA_MARIA_IMG_9564.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '5',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/VILLA MARIA__Pune/VILLA_MARIA_IMG_9568.jpg',
          altText: 'VILLA_MARIA_IMG_9568.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '6',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/VILLA MARIA__Pune/VILLA_MARIA_IMG_9647.jpg',
          altText: 'VILLA_MARIA_IMG_9647.jpg',
          width: 1920,
          height: 1263,
        },
        {
          id: '7',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/VILLA MARIA__Pune/VILLA_MARIA_IMG_9670.jpg',
          altText: 'VILLA_MARIA_IMG_9670.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '8',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/VILLA MARIA__Pune/VILLA_MARIA_IMG_9671.jpg',
          altText: 'VILLA_MARIA_IMG_9671.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '9',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/VILLA MARIA__Pune/VILLA_MARIA_IMG_9672.jpg',
          altText: 'VILLA_MARIA_IMG_9672.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '10',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/homesAndSpaces/VILLA MARIA__Pune/VILLA_MARIA_IMG_9695.jpg',
          altText: 'VILLA_MARIA_IMG_9695.jpg',
          width: 1280,
          height: 1920,
        },
      ],
      previous: { collectionId: '15', title: 'THE TERRACE GARDEN' },
      next: { collectionId: '0', title: 'CLUB AMSTORIA' },
      collectionId: '16',
      title: 'Villa Maria',
    },
  ] as IPhotoCollection[];
