import { IPhotoCollection } from '@siddhesh-savant-photography/models';

export const megaProjectsCollections = () =>
  [
    {
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Atal Setu__Nhava Sheva/Atal_Setu_COVER.jpg',
      thumbnailAltText: 'Atal_Setu_COVER.jpg',
      description: 'Nhava Sheva',
      eager: false,
      width: 1920,
      height: 1080,
      photos: [
        {
          id: '0',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Atal Setu__Nhava Sheva/Atal_Setu_COVER.jpg',
          altText: 'Atal_Setu_COVER.jpg',
          width: 1920,
          height: 1080,
        },
        {
          id: '1',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Atal Setu__Nhava Sheva/Atal_Setu_DJI_20231215165239_0013_D.jpg',
          altText: 'Atal_Setu_DJI_20231215165239_0013_D.jpg',
          width: 1920,
          height: 1080,
        },
        {
          id: '2',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Atal Setu__Nhava Sheva/Atal_Setu_DJI_20231215165658_0020_D.jpg',
          altText: 'Atal_Setu_DJI_20231215165658_0020_D.jpg',
          width: 1920,
          height: 1080,
        },
        {
          id: '3',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Atal Setu__Nhava Sheva/Atal_Setu_DJI_20231215171509_0031_D.jpg',
          altText: 'Atal_Setu_DJI_20231215171509_0031_D.jpg',
          width: 1920,
          height: 1080,
        },
        {
          id: '4',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Atal Setu__Nhava Sheva/Atal_Setu_DJI_20231215174356_0058_D.jpg',
          altText: 'Atal_Setu_DJI_20231215174356_0058_D.jpg',
          width: 1920,
          height: 1080,
        },
        {
          id: '5',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Atal Setu__Nhava Sheva/Atal_Setu_DJI_20231216070841_0016_D.jpg',
          altText: 'Atal_Setu_DJI_20231216070841_0016_D.jpg',
          width: 1920,
          height: 1080,
        },
        {
          id: '6',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Atal Setu__Nhava Sheva/Atal_Setu_DJI_20231216072228_0022_D.jpg',
          altText: 'Atal_Setu_DJI_20231216072228_0022_D.jpg',
          width: 1920,
          height: 1080,
        },
        {
          id: '7',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Atal Setu__Nhava Sheva/Atal_Setu_DJI_20231216083627_0082_D.jpg',
          altText: 'Atal_Setu_DJI_20231216083627_0082_D.jpg',
          width: 1920,
          height: 1080,
        },
        {
          id: '8',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Atal Setu__Nhava Sheva/Atal_Setu_DJI_20231216084009_0087_D -1.jpg',
          altText: 'Atal_Setu_DJI_20231216084009_0087_D -1.jpg',
          width: 1920,
          height: 1080,
        },
        {
          id: '9',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Atal Setu__Nhava Sheva/Atal_Setu_DJI_20231216084619_0092_D.jpg',
          altText: 'Atal_Setu_DJI_20231216084619_0092_D.jpg',
          width: 1920,
          height: 1080,
        },
      ],
      previous: {
        collectionId: '1',
        title: 'Chhatrapati Shivaji Maharaj International Airport',
      },
      next: {
        collectionId: '1',
        title: 'Chhatrapati Shivaji Maharaj International Airport',
      },
      collectionId: '0',
      title: 'Atal Setu',
    },
    {
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Chhatrapati Shivaji Maharaj International Airport__Mumbai/Chhatrapati_Shivaji_Maharaj_International_Airport_COVER.jpg',
      thumbnailAltText:
        'Chhatrapati_Shivaji_Maharaj_International_Airport_COVER.jpg',
      description: 'Mumbai',
      eager: false,
      width: 1755,
      height: 1280,
      photos: [
        {
          id: '0',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Chhatrapati Shivaji Maharaj International Airport__Mumbai/Chhatrapati_Shivaji_Maharaj_International_Airport_COVER.jpg',
          altText:
            'Chhatrapati_Shivaji_Maharaj_International_Airport_COVER.jpg',
          width: 1755,
          height: 1280,
        },
        {
          id: '1',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Chhatrapati Shivaji Maharaj International Airport__Mumbai/Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_0051.jpg',
          altText:
            'Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_0051.jpg',
          width: 1900,
          height: 1280,
        },
        {
          id: '2',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Chhatrapati Shivaji Maharaj International Airport__Mumbai/Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_0073.jpg',
          altText:
            'Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_0073.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '3',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Chhatrapati Shivaji Maharaj International Airport__Mumbai/Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_0077.jpg',
          altText:
            'Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_0077.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '4',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Chhatrapati Shivaji Maharaj International Airport__Mumbai/Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_0090.jpg',
          altText:
            'Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_0090.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '5',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Chhatrapati Shivaji Maharaj International Airport__Mumbai/Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_0094.jpg',
          altText:
            'Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_0094.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '6',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Chhatrapati Shivaji Maharaj International Airport__Mumbai/Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_0103.jpg',
          altText:
            'Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_0103.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '7',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Chhatrapati Shivaji Maharaj International Airport__Mumbai/Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_1613.jpg',
          altText:
            'Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_1613.jpg',
          width: 1920,
          height: 1264,
        },
        {
          id: '8',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Chhatrapati Shivaji Maharaj International Airport__Mumbai/Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_1947.jpg',
          altText:
            'Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_1947.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '9',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Chhatrapati Shivaji Maharaj International Airport__Mumbai/Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_1951.jpg',
          altText:
            'Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_1951.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '10',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Chhatrapati Shivaji Maharaj International Airport__Mumbai/Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_1960.jpg',
          altText:
            'Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_1960.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '11',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Chhatrapati Shivaji Maharaj International Airport__Mumbai/Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_2206.jpg',
          altText:
            'Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_2206.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '12',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Chhatrapati Shivaji Maharaj International Airport__Mumbai/Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_2211.jpg',
          altText:
            'Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_2211.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '13',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Chhatrapati Shivaji Maharaj International Airport__Mumbai/Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_3715.jpg',
          altText:
            'Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_3715.jpg',
          width: 1920,
          height: 1263,
        },
        {
          id: '14',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Chhatrapati Shivaji Maharaj International Airport__Mumbai/Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_4062.jpg',
          altText:
            'Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_4062.jpg',
          width: 1920,
          height: 1279,
        },
        {
          id: '15',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Chhatrapati Shivaji Maharaj International Airport__Mumbai/Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_4247.jpg',
          altText:
            'Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_4247.jpg',
          width: 1920,
          height: 1264,
        },
        {
          id: '16',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Chhatrapati Shivaji Maharaj International Airport__Mumbai/Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_4567.jpg',
          altText:
            'Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_4567.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '17',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Chhatrapati Shivaji Maharaj International Airport__Mumbai/Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_5826.jpg',
          altText:
            'Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_5826.jpg',
          width: 1280,
          height: 1835,
        },
        {
          id: '18',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Chhatrapati Shivaji Maharaj International Airport__Mumbai/Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_5990.jpg',
          altText:
            'Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_5990.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '19',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Chhatrapati Shivaji Maharaj International Airport__Mumbai/Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_6020.jpg',
          altText:
            'Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_6020.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '20',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Chhatrapati Shivaji Maharaj International Airport__Mumbai/Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_6031.jpg',
          altText:
            'Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_6031.jpg',
          width: 1920,
          height: 1280,
        },
        {
          id: '21',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Chhatrapati Shivaji Maharaj International Airport__Mumbai/Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_6702.jpg',
          altText:
            'Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_6702.jpg',
          width: 1280,
          height: 1920,
        },
        {
          id: '22',
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images1/megaProjects/Chhatrapati Shivaji Maharaj International Airport__Mumbai/Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_7389.jpg',
          altText:
            'Chhatrapati_Shivaji_Maharaj_International_Airport_IMG_7389.jpg',
          width: 1920,
          height: 1280,
        },
      ],
      previous: { collectionId: '0', title: 'Atal Setu' },
      next: { collectionId: '0', title: 'Atal Setu' },
      collectionId: '1',
      title: 'Chhatrapati Shivaji Maharaj International Airport',
    },
  ] as IPhotoCollection[];
