import { IPhoto, IPhotoCollection } from '@siddhesh-savant-photography/models';

export const collections = () =>
  [
    {
      collectionId: '1',
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/DEANNE_S+HOUSE/01-04-20238353.jpg',
      thumbnailAltText: "Deanne's House Collection Thumbnail",
      title: "Deanne's House",
      description: '',
      photos: [
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/DEANNE_S+HOUSE/01-04-20238353.jpg',
          altText: 'image-1',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/DEANNE_S+HOUSE/01-04-20238355.jpg',
          altText: 'image-2',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/DEANNE_S+HOUSE/1Q0A0149.jpg',
          altText: 'image-3',
        },
      ],
    },
    {
      collectionId: '2',
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/KARISHMA_S+HOUSE/1Q0A1907.jpg',
      thumbnailAltText: "Karishma's House Collection Thumbnail",
      title: "Karishma's House",
      description: '',
      photos: [
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/KARISHMA_S+HOUSE/1Q0A1904.jpg',
          altText: 'image-1',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/KARISHMA_S+HOUSE/1Q0A1907.jpg',
          altText: 'image-2',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/KARISHMA_S+HOUSE/1Q0A1915.jpg',
          altText: 'image-3',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/KARISHMA_S+HOUSE/1Q0A1923.jpg',
          altText: 'image-4',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/KARISHMA_S+HOUSE/1Q0A1932.jpg',
          altText: 'image-5',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/KARISHMA_S+HOUSE/1Q0A1940.jpg',
          altText: 'image-6',
        },
      ],
    },
    {
      collectionId: '3',
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/PURNS+HOUSE/1Q0A3145.jpg',
      thumbnailAltText: "Purn's House Collection Thumbnail",
      title: "Purn's House",
      description: '',
      photos: [
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/PURNS+HOUSE/1Q0A3087.jpg',
          altText: 'image-1',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/PURNS+HOUSE/1Q0A3143.jpg',
          altText: 'image-2',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/PURNS+HOUSE/1Q0A3145.jpg',
          altText: 'image-3',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/PURNS+HOUSE/1Q0A3208.jpg',
          altText: 'image-3',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/PURNS+HOUSE/1Q0A3236.jpg',
          altText: 'image-3',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/PURNS+HOUSE/1Q0A3242.jpg',
          altText: 'image-3',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/PURNS+HOUSE/1Q0A3259.jpg',
          altText: 'image-3',
        },
      ],
    },
    {
      collectionId: '4',
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/RITAKSHI+HOUSE+JPEG/IMG_6350.jpg',
      thumbnailAltText: "Ritakshi's House Collection Thumbnail",
      title: "Ritakshi's House",
      description: '',
      photos: [
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/RITAKSHI+HOUSE+JPEG/IMG_6303.jpg',
          altText: 'image-1',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/RITAKSHI+HOUSE+JPEG/IMG_6318.jpg',
          altText: 'image-2',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/RITAKSHI+HOUSE+JPEG/IMG_6348.jpg',
          altText: 'image-3',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/RITAKSHI+HOUSE+JPEG/IMG_6350.jpg',
          altText: 'image-4',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/RITAKSHI+HOUSE+JPEG/IMG_6362.jpg',
          altText: 'image-5',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/RITAKSHI+HOUSE+JPEG/IMG_6379.jpg',
          altText: 'image-6',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/RITAKSHI+HOUSE+JPEG/IMG_6380.jpg',
          altText: 'image-7',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/RITAKSHI+HOUSE+JPEG/IMG_6380.jpg',
          altText: 'image-7',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/RITAKSHI+HOUSE+JPEG/IMG_6386.jpg',
          altText: 'image-7',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/RITAKSHI+HOUSE+JPEG/IMG_6380.jpg',
          altText: 'image-7',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/RITAKSHI+HOUSE+JPEG/IMG_6389.jpg',
          altText: 'image-7',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/RITAKSHI+HOUSE+JPEG/IMG_6391.jpg',
          altText: 'image-7',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/RITAKSHI+HOUSE+JPEG/IMG_6411.jpg',
          altText: 'image-7',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/RITAKSHI+HOUSE+JPEG/IMG_6419.jpg',
          altText: 'image-7',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/RITAKSHI+HOUSE+JPEG/IMG_6428.jpg',
          altText: 'image-7',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/RITAKSHI+HOUSE+JPEG/IMG_6437.jpg',
          altText: 'image-7',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/RITAKSHI+HOUSE+JPEG/IMG_6485.jpg',
          altText: 'image-7',
        },
      ],
    },
    {
      collectionId: '5',
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/RITAKSHI+OFFICE+JPEG/IMG_6509.jpg',
      thumbnailAltText: "Ritakshi's Office Collection Thumbnail",
      title: "Ritakshi's Office",
      description: '',
      photos: [
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/RITAKSHI+OFFICE+JPEG/IMG_6504.jpg',
          altText: 'image-1',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/RITAKSHI+OFFICE+JPEG/IMG_6509.jpg',
          altText: 'image-2',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/RITAKSHI+OFFICE+JPEG/IMG_6514.jpg',
          altText: 'image-3',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/RITAKSHI+OFFICE+JPEG/IMG_6593.jpg',
          altText: 'image-4',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/RITAKSHI+OFFICE+JPEG/IMG_6599.jpg',
          altText: 'image-5',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/RITAKSHI+OFFICE+JPEG/IMG_6606.jpg',
          altText: 'image-6',
        },
      ],
    },
    {
      collectionId: '6',
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/SHONA+NATH+JPEG/IMG_6852.jpg',
      thumbnailAltText: 'Sona Nath Collection Thumbnail',
      title: 'Sona Nath',
      description: '',
      photos: [
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/SHONA+NATH+JPEG/IMG_6835.jpg',
          altText: 'image-1',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/SHONA+NATH+JPEG/IMG_6852.jpg',
          altText: 'image-2',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/SHONA+NATH+JPEG/IMG_6856.jpg',
          altText: 'image-3',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/SHONA+NATH+JPEG/IMG_6860.jpg',
          altText: 'image-4',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/SHONA+NATH+JPEG/IMG_6865.jpg',
          altText: 'image-5',
        },
      ],
    },
    {
      collectionId: '7',
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/TANUJA+%26+ASSOCIATES+JPEG/IMG_0216.jpg',
      thumbnailAltText: 'Tanuja & Associates Collection Thumbnail',
      title: 'Tanuja & Associates',
      description: '',
      photos: [
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/TANUJA+%26+ASSOCIATES+JPEG/IMG_0216.jpg',
          altText: 'image-1',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/TANUJA+%26+ASSOCIATES+JPEG/IMG_0250.jpg',
          altText: 'image-2',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/TANUJA+%26+ASSOCIATES+JPEG/IMG_0262.jpg',
          altText: 'image-3',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/TANUJA+%26+ASSOCIATES+JPEG/IMG_0289.jpg',
          altText: 'image-4',
        },
      ],
    },
    {
      collectionId: '8',
      thumbnailUrl:
        'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/White+House/PG5A7472.jpg',
      thumbnailAltText: 'White House Collection Thumbnail',
      title: 'White House',
      description: '',
      photos: [
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/White+House/PG5A7378.jpg',
          altText: 'image-1',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/White+House/PG5A790.jpg',
          altText: 'image-2',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/White+House/PG5A796.jpg',
          altText: 'image-3',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/White+House/PG5A7443.jpg',
          altText: 'image-4',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/White+House/PG5A7459.jpg',
          altText: 'image-5',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/White+House/PG5A7472.jpg',
          altText: 'image-6',
        },
        {
          title: '',
          description: '',
          url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/collections/White+House/PG5A7729.jpg',
          altText: 'image-7',
        },
      ],
    },
  ] as IPhotoCollection[];

export const photos = () =>
  [
    {
      id: '0',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/10_RITAKSHI_OFFICE_IMG_6504.jpg',
      altText: '10_RITAKSHI_OFFICE_IMG_6504.jpg',
      width: 1920,
      height: 1263,
    },
    {
      id: '1',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/10_RITAKSHI_OFFICE_IMG_6509.jpg',
      altText: '10_RITAKSHI_OFFICE_IMG_6509.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '2',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/10_RITAKSHI_OFFICE_IMG_6514.jpg',
      altText: '10_RITAKSHI_OFFICE_IMG_6514.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '3',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/10_RITAKSHI_OFFICE_IMG_6593.jpg',
      altText: '10_RITAKSHI_OFFICE_IMG_6593.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '4',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/10_RITAKSHI_OFFICE_IMG_6599.jpg',
      altText: '10_RITAKSHI_OFFICE_IMG_6599.jpg',
      width: 1920,
      height: 1263,
    },
    {
      id: '5',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/10_RITAKSHI_OFFICE_IMG_6605.jpg',
      altText: '10_RITAKSHI_OFFICE_IMG_6605.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '6',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/10_RITAKSHI_OFFICE_IMG_6606.jpg',
      altText: '10_RITAKSHI_OFFICE_IMG_6606.jpg',
      width: 1920,
      height: 1263,
    },
    {
      id: '7',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/11_SHONA_NATH_IMG_6835.jpg',
      altText: '11_SHONA_NATH_IMG_6835.jpg',
      width: 1920,
      height: 1263,
    },
    {
      id: '8',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/11_SHONA_NATH_IMG_6856.jpg',
      altText: '11_SHONA_NATH_IMG_6856.jpg',
      width: 1920,
      height: 1263,
    },
    {
      id: '9',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/11_SHONA_NATH_IMG_6860.jpg',
      altText: '11_SHONA_NATH_IMG_6860.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '10',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/11_SHONA_NATH_IMG_6865.jpg',
      altText: '11_SHONA_NATH_IMG_6865.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '11',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/12_TANUJA_IMG_0216.jpg',
      altText: '12_TANUJA_IMG_0216.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '12',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/12_TANUJA_IMG_0250.jpg',
      altText: '12_TANUJA_IMG_0250.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '13',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/12_TANUJA_IMG_0262.jpg',
      altText: '12_TANUJA_IMG_0262.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '14',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/12_TANUJA_IMG_0289.jpg',
      altText: '12_TANUJA_IMG_0289.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '15',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/13_AMSTORIA_IMG_6633.jpg',
      altText: '13_AMSTORIA_IMG_6633.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '16',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/13_AMSTORIA_IMG_6641.jpg',
      altText: '13_AMSTORIA_IMG_6641.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '17',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/13_AMSTORIA_IMG_6668.jpg',
      altText: '13_AMSTORIA_IMG_6668.jpg',
      width: 1920,
      height: 1263,
    },
    {
      id: '18',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/13_AMSTORIA_IMG_6683.jpg',
      altText: '13_AMSTORIA_IMG_6683.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '19',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/13_AMSTORIA_IMG_6684.jpg',
      altText: '13_AMSTORIA_IMG_6684.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '20',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/13_AMSTORIA_IMG_6690.jpg',
      altText: '13_AMSTORIA_IMG_6690.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '21',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/13_AMSTORIA_IMG_6698.jpg',
      altText: '13_AMSTORIA_IMG_6698.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '22',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/13_AMSTORIA_IMG_6701.jpg',
      altText: '13_AMSTORIA_IMG_6701.jpg',
      width: 1920,
      height: 1263,
    },
    {
      id: '23',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/13_AMSTORIA_IMG_6703.jpg',
      altText: '13_AMSTORIA_IMG_6703.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '24',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/13_AMSTORIA_IMG_6706.jpg',
      altText: '13_AMSTORIA_IMG_6706.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '25',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/13_AMSTORIA_IMG_6711.jpg',
      altText: '13_AMSTORIA_IMG_6711.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '26',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/13_AMSTORIA_IMG_6715.jpg',
      altText: '13_AMSTORIA_IMG_6715.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '27',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/13_AMSTORIA_IMG_6716.jpg',
      altText: '13_AMSTORIA_IMG_6716.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '28',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/13_AMSTORIA_IMG_6723.jpg',
      altText: '13_AMSTORIA_IMG_6723.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '29',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/13_AMSTORIA_IMG_6727.jpg',
      altText: '13_AMSTORIA_IMG_6727.jpg',
      width: 1920,
      height: 1263,
    },
    {
      id: '30',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/13_AMSTORIA_IMG_6732.jpg',
      altText: '13_AMSTORIA_IMG_6732.jpg',
      width: 1920,
      height: 1263,
    },
    {
      id: '31',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/13_AMSTORIA_IMG_6734.jpg',
      altText: '13_AMSTORIA_IMG_6734.jpg',
      width: 1920,
      height: 1259,
    },
    {
      id: '32',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/13_AMSTORIA_IMG_6737.jpg',
      altText: '13_AMSTORIA_IMG_6737.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '33',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/13_AMSTORIA_IMG_6741.jpg',
      altText: '13_AMSTORIA_IMG_6741.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '34',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/13_AMSTORIA_IMG_6756.jpg',
      altText: '13_AMSTORIA_IMG_6756.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '35',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/13_AMSTORIA_IMG_6758.jpg',
      altText: '13_AMSTORIA_IMG_6758.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '36',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/13_AMSTORIA_IMG_6760.jpg',
      altText: '13_AMSTORIA_IMG_6760.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '37',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/13_AMSTORIA_IMG_6765.jpg',
      altText: '13_AMSTORIA_IMG_6765.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '38',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/1_MOIRA_GOA_1Q0A1610.jpg',
      altText: '1_MOIRA_GOA_1Q0A1610.jpg',
      width: 1280,
      height: 853,
    },
    {
      id: '39',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/1_MOIRA_GOA_1Q0A1631.jpg',
      altText: '1_MOIRA_GOA_1Q0A1631.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '40',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/1_MOIRA_GOA_1Q0A1643.jpg',
      altText: '1_MOIRA_GOA_1Q0A1643.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '41',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/1_MOIRA_GOA_1Q0A1645.jpg',
      altText: '1_MOIRA_GOA_1Q0A1645.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '42',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/1_MOIRA_GOA_1Q0A1649.jpg',
      altText: '1_MOIRA_GOA_1Q0A1649.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '43',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/1_MOIRA_GOA_1Q0A1653.jpg',
      altText: '1_MOIRA_GOA_1Q0A1653.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '44',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/1_MOIRA_GOA_1Q0A1724.jpg',
      altText: '1_MOIRA_GOA_1Q0A1724.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '45',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/1_MOIRA_GOA_1Q0A1752.jpg',
      altText: '1_MOIRA_GOA_1Q0A1752.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '46',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/1_MOIRA_GOA_1Q0A1778.jpg',
      altText: '1_MOIRA_GOA_1Q0A1778.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '47',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/1_MOIRA_GOA_1Q0A1788.jpg',
      altText: '1_MOIRA_GOA_1Q0A1788.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '48',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/1_MOIRA_GOA_1Q0A1808.jpg',
      altText: '1_MOIRA_GOA_1Q0A1808.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '49',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/1_MOIRA_GOA_MOIRA GOA0071.jpg',
      altText: '1_MOIRA_GOA_MOIRA GOA0071.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '50',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/1_MOIRA_GOA_MOIRA GOA0093.jpg',
      altText: '1_MOIRA_GOA_MOIRA GOA0093.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '51',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/1_MOIRA_GOA_MOIRA GOA0106.jpg',
      altText: '1_MOIRA_GOA_MOIRA GOA0106.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '52',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/1_MOIRA_GOA_MOIRA GOA0112.jpg',
      altText: '1_MOIRA_GOA_MOIRA GOA0112.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '53',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/1_MOIRA_GOA_MOIRA GOA0123.jpg',
      altText: '1_MOIRA_GOA_MOIRA GOA0123.jpg',
      width: 1280,
      height: 853,
    },
    {
      id: '54',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/1_MOIRA_GOA_MOIRA GOA0159.jpg',
      altText: '1_MOIRA_GOA_MOIRA GOA0159.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '55',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/1_MOIRA_GOA_MOIRA GOA0167.jpg',
      altText: '1_MOIRA_GOA_MOIRA GOA0167.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '56',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/1_MOIRA_GOA_MOIRA GOA0177.jpg',
      altText: '1_MOIRA_GOA_MOIRA GOA0177.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '57',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/1_MOIRA_GOA_MOIRA GOA0183.jpg',
      altText: '1_MOIRA_GOA_MOIRA GOA0183.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '58',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/1_MOIRA_GOA_MOIRA GOA0192.jpg',
      altText: '1_MOIRA_GOA_MOIRA GOA0192.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '59',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/2_DAPOLI_IMG_4345.jpg',
      altText: '2_DAPOLI_IMG_4345.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '60',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/2_DAPOLI_IMG_4362.jpg',
      altText: '2_DAPOLI_IMG_4362.jpg',
      width: 1263,
      height: 1920,
    },
    {
      id: '61',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/2_DAPOLI_IMG_4366.jpg',
      altText: '2_DAPOLI_IMG_4366.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '62',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/2_DAPOLI_IMG_4396.jpg',
      altText: '2_DAPOLI_IMG_4396.jpg',
      width: 1919,
      height: 1280,
    },
    {
      id: '63',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/2_DAPOLI_IMG_4410.jpg',
      altText: '2_DAPOLI_IMG_4410.jpg',
      width: 1278,
      height: 1920,
    },
    {
      id: '64',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/2_DAPOLI_IMG_4469.jpg',
      altText: '2_DAPOLI_IMG_4469.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '65',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/2_DAPOLI_IMG_4488.jpg',
      altText: '2_DAPOLI_IMG_4488.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '66',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/2_DAPOLI_IMG_4495.jpg',
      altText: '2_DAPOLI_IMG_4495.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '67',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/2_DAPOLI_IMG_4508.jpg',
      altText: '2_DAPOLI_IMG_4508.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '68',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/2_DAPOLI_IMG_4512.jpg',
      altText: '2_DAPOLI_IMG_4512.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '69',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/2_DAPOLI_IMG_4521.jpg',
      altText: '2_DAPOLI_IMG_4521.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '70',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/2_DAPOLI_IMG_4531.jpg',
      altText: '2_DAPOLI_IMG_4531.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '71',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/2_DAPOLI_IMG_4534.jpg',
      altText: '2_DAPOLI_IMG_4534.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '72',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/2_DAPOLI_IMG_4537.jpg',
      altText: '2_DAPOLI_IMG_4537.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '73',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/2_DAPOLI_IMG_4893.jpg',
      altText: '2_DAPOLI_IMG_4893.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '74',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/2_DAPOLI_IMG_4896.jpg',
      altText: '2_DAPOLI_IMG_4896.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '75',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9746.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9746.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '76',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9749.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9749.jpg',
      width: 1920,
      height: 1266,
    },
    {
      id: '77',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9765.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9765.jpg',
      width: 1920,
      height: 1266,
    },
    {
      id: '78',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9792.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9792.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '79',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9804.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9804.jpg',
      width: 1920,
      height: 1266,
    },
    {
      id: '80',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9813.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9813.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '81',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9826.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9826.jpg',
      width: 1920,
      height: 1266,
    },
    {
      id: '82',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9828.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9828.jpg',
      width: 1920,
      height: 1266,
    },
    {
      id: '83',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9839.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9839.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '84',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9855.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9855.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '85',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9859.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9859.jpg',
      width: 1920,
      height: 1266,
    },
    {
      id: '86',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9863.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9863.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '87',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9864.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9864.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '88',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9872.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9872.jpg',
      width: 1920,
      height: 1266,
    },
    {
      id: '89',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9875.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9875.jpg',
      width: 1920,
      height: 1266,
    },
    {
      id: '90',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9877.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9877.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '91',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9890.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9890.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '92',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9895.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9895.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '93',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9899.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9899.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '94',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9900.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9900.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '95',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9906.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9906.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '96',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9907.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9907.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '97',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9909.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9909.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '98',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9910.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9910.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '99',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9913.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9913.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '100',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9920.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9920.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '101',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9923.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9923.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '102',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9931.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9931.jpg',
      width: 1266,
      height: 1920,
    },
    {
      id: '103',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9934.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9934.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '104',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9935.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9935.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '105',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9937.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9937.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '106',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/3_PRIAMAL_ARANYA_1Q0A9948.jpg',
      altText: '3_PRIAMAL_ARANYA_1Q0A9948.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '107',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/4_DEANNES_HOUSE_01-04-20238353.jpg',
      altText: '4_DEANNES_HOUSE_01-04-20238353.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '108',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/4_DEANNES_HOUSE_01-04-20238355.jpg',
      altText: '4_DEANNES_HOUSE_01-04-20238355.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '109',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/4_DEANNES_HOUSE_01-04-20238364.jpg',
      altText: '4_DEANNES_HOUSE_01-04-20238364.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '110',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/4_DEANNES_HOUSE_01-04-20238371 1.jpg',
      altText: '4_DEANNES_HOUSE_01-04-20238371 1.jpg',
      width: 1280,
      height: 853,
    },
    {
      id: '111',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/4_DEANNES_HOUSE_01-04-20238371.jpg',
      altText: '4_DEANNES_HOUSE_01-04-20238371.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '112',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/4_DEANNES_HOUSE_1Q0A0138.jpg',
      altText: '4_DEANNES_HOUSE_1Q0A0138.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '113',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/4_DEANNES_HOUSE_1Q0A0149.jpg',
      altText: '4_DEANNES_HOUSE_1Q0A0149.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '114',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/4_DEANNES_HOUSE_1Q0A0166.jpg',
      altText: '4_DEANNES_HOUSE_1Q0A0166.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '115',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/4_DEANNES_HOUSE_1Q0A1047.jpg',
      altText: '4_DEANNES_HOUSE_1Q0A1047.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '116',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/4_DEANNES_HOUSE_1Q0A1157.jpg',
      altText: '4_DEANNES_HOUSE_1Q0A1157.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '117',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/4_DEANNES_HOUSE_1Q0A1167.jpg',
      altText: '4_DEANNES_HOUSE_1Q0A1167.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '118',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/4_DEANNES_HOUSE_DEANNE_S House 27-04-230093.jpg',
      altText: '4_DEANNES_HOUSE_DEANNE_S House 27-04-230093.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '119',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/4_DEANNES_HOUSE_DEANNE_S House 27-04-230113.jpg',
      altText: '4_DEANNES_HOUSE_DEANNE_S House 27-04-230113.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '120',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/4_DEANNES_HOUSE_DEANNE_S House 27-04-230124.jpg',
      altText: '4_DEANNES_HOUSE_DEANNE_S House 27-04-230124.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '121',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/4_DEANNES_HOUSE_DEANNE_S House 27-04-230129.jpg',
      altText: '4_DEANNES_HOUSE_DEANNE_S House 27-04-230129.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '122',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/4_DEANNES_HOUSE_DEANNE_S House 27-04-230133.jpg',
      altText: '4_DEANNES_HOUSE_DEANNE_S House 27-04-230133.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '123',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/5_PURNS_HOUSE_1Q0A3087.jpg',
      altText: '5_PURNS_HOUSE_1Q0A3087.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '124',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/5_PURNS_HOUSE_1Q0A3143.jpg',
      altText: '5_PURNS_HOUSE_1Q0A3143.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '125',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/5_PURNS_HOUSE_1Q0A3145.jpg',
      altText: '5_PURNS_HOUSE_1Q0A3145.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '126',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/5_PURNS_HOUSE_1Q0A3196.jpg',
      altText: '5_PURNS_HOUSE_1Q0A3196.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '127',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/5_PURNS_HOUSE_1Q0A3208.jpg',
      altText: '5_PURNS_HOUSE_1Q0A3208.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '128',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/5_PURNS_HOUSE_1Q0A3215.jpg',
      altText: '5_PURNS_HOUSE_1Q0A3215.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '129',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/5_PURNS_HOUSE_1Q0A3236.jpg',
      altText: '5_PURNS_HOUSE_1Q0A3236.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '130',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/5_PURNS_HOUSE_1Q0A3242.jpg',
      altText: '5_PURNS_HOUSE_1Q0A3242.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '131',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/5_PURNS_HOUSE_1Q0A3259.jpg',
      altText: '5_PURNS_HOUSE_1Q0A3259.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '132',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/6_RAVISH_KAPOOR_OFFICE_IMG_7382.jpg',
      altText: '6_RAVISH_KAPOOR_OFFICE_IMG_7382.jpg',
      width: 1920,
      height: 1263,
    },
    {
      id: '133',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/6_RAVISH_KAPOOR_OFFICE_IMG_7386.jpg',
      altText: '6_RAVISH_KAPOOR_OFFICE_IMG_7386.jpg',
      width: 1920,
      height: 1263,
    },
    {
      id: '134',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/6_RAVISH_KAPOOR_OFFICE_IMG_7397.jpg',
      altText: '6_RAVISH_KAPOOR_OFFICE_IMG_7397.jpg',
      width: 1920,
      height: 1263,
    },
    {
      id: '135',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/6_RAVISH_KAPOOR_OFFICE_IMG_7408.jpg',
      altText: '6_RAVISH_KAPOOR_OFFICE_IMG_7408.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '136',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/6_RAVISH_KAPOOR_OFFICE_IMG_7418.jpg',
      altText: '6_RAVISH_KAPOOR_OFFICE_IMG_7418.jpg',
      width: 1920,
      height: 1263,
    },
    {
      id: '137',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/7_KARISHMA_HOME_1Q0A1904.jpg',
      altText: '7_KARISHMA_HOME_1Q0A1904.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '138',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/7_KARISHMA_HOME_1Q0A1907.jpg',
      altText: '7_KARISHMA_HOME_1Q0A1907.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '139',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/7_KARISHMA_HOME_1Q0A1915.jpg',
      altText: '7_KARISHMA_HOME_1Q0A1915.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '140',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/7_KARISHMA_HOME_1Q0A1923.jpg',
      altText: '7_KARISHMA_HOME_1Q0A1923.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '141',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/7_KARISHMA_HOME_1Q0A1932.jpg',
      altText: '7_KARISHMA_HOME_1Q0A1932.jpg',
      width: 1686,
      height: 1280,
    },
    {
      id: '142',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/7_KARISHMA_HOME_1Q0A1940.jpg',
      altText: '7_KARISHMA_HOME_1Q0A1940.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '143',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/8_MUMBAI_AIRPORT_IMG_0051.jpg',
      altText: '8_MUMBAI_AIRPORT_IMG_0051.jpg',
      width: 1900,
      height: 1280,
    },
    {
      id: '144',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/8_MUMBAI_AIRPORT_IMG_0073.jpg',
      altText: '8_MUMBAI_AIRPORT_IMG_0073.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '145',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/8_MUMBAI_AIRPORT_IMG_0077.jpg',
      altText: '8_MUMBAI_AIRPORT_IMG_0077.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '146',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/8_MUMBAI_AIRPORT_IMG_0090.jpg',
      altText: '8_MUMBAI_AIRPORT_IMG_0090.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '147',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/8_MUMBAI_AIRPORT_IMG_0094.jpg',
      altText: '8_MUMBAI_AIRPORT_IMG_0094.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '148',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/8_MUMBAI_AIRPORT_IMG_0103.jpg',
      altText: '8_MUMBAI_AIRPORT_IMG_0103.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '149',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/8_MUMBAI_AIRPORT_IMG_1613.jpg',
      altText: '8_MUMBAI_AIRPORT_IMG_1613.jpg',
      width: 1920,
      height: 1264,
    },
    {
      id: '150',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/8_MUMBAI_AIRPORT_IMG_1947.jpg',
      altText: '8_MUMBAI_AIRPORT_IMG_1947.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '151',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/8_MUMBAI_AIRPORT_IMG_1951.jpg',
      altText: '8_MUMBAI_AIRPORT_IMG_1951.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '152',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/8_MUMBAI_AIRPORT_IMG_1960.jpg',
      altText: '8_MUMBAI_AIRPORT_IMG_1960.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '153',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/8_MUMBAI_AIRPORT_IMG_2206.jpg',
      altText: '8_MUMBAI_AIRPORT_IMG_2206.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '154',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/8_MUMBAI_AIRPORT_IMG_2211.jpg',
      altText: '8_MUMBAI_AIRPORT_IMG_2211.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '155',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/8_MUMBAI_AIRPORT_IMG_3715.jpg',
      altText: '8_MUMBAI_AIRPORT_IMG_3715.jpg',
      width: 1920,
      height: 1263,
    },
    {
      id: '156',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/8_MUMBAI_AIRPORT_IMG_4062.jpg',
      altText: '8_MUMBAI_AIRPORT_IMG_4062.jpg',
      width: 1920,
      height: 1279,
    },
    {
      id: '157',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/8_MUMBAI_AIRPORT_IMG_4247.jpg',
      altText: '8_MUMBAI_AIRPORT_IMG_4247.jpg',
      width: 1920,
      height: 1264,
    },
    {
      id: '158',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/8_MUMBAI_AIRPORT_IMG_4567.jpg',
      altText: '8_MUMBAI_AIRPORT_IMG_4567.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '159',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/8_MUMBAI_AIRPORT_IMG_5826.jpg',
      altText: '8_MUMBAI_AIRPORT_IMG_5826.jpg',
      width: 1280,
      height: 1835,
    },
    {
      id: '160',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/8_MUMBAI_AIRPORT_IMG_5990.jpg',
      altText: '8_MUMBAI_AIRPORT_IMG_5990.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '161',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/8_MUMBAI_AIRPORT_IMG_6020.jpg',
      altText: '8_MUMBAI_AIRPORT_IMG_6020.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '162',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/8_MUMBAI_AIRPORT_IMG_6031.jpg',
      altText: '8_MUMBAI_AIRPORT_IMG_6031.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '163',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/8_MUMBAI_AIRPORT_IMG_6702.jpg',
      altText: '8_MUMBAI_AIRPORT_IMG_6702.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '164',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/8_MUMBAI_AIRPORT_IMG_7389.jpg',
      altText: '8_MUMBAI_AIRPORT_IMG_7389.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '165',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/8_MUMBAI_AIRPORT_IMG_9888.jpg',
      altText: '8_MUMBAI_AIRPORT_IMG_9888.jpg',
      width: 1755,
      height: 1280,
    },
    {
      id: '166',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/9_RITAKSHI_HOUSE_IMG_6303.jpg',
      altText: '9_RITAKSHI_HOUSE_IMG_6303.jpg',
      width: 1620,
      height: 1080,
    },
    {
      id: '167',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/9_RITAKSHI_HOUSE_IMG_6318.jpg',
      altText: '9_RITAKSHI_HOUSE_IMG_6318.jpg',
      width: 1642,
      height: 1080,
    },
    {
      id: '168',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/9_RITAKSHI_HOUSE_IMG_6348.jpg',
      altText: '9_RITAKSHI_HOUSE_IMG_6348.jpg',
      width: 1256,
      height: 1920,
    },
    {
      id: '169',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/9_RITAKSHI_HOUSE_IMG_6350.jpg',
      altText: '9_RITAKSHI_HOUSE_IMG_6350.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '170',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/9_RITAKSHI_HOUSE_IMG_6362.jpg',
      altText: '9_RITAKSHI_HOUSE_IMG_6362.jpg',
      width: 1636,
      height: 1080,
    },
    {
      id: '171',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/9_RITAKSHI_HOUSE_IMG_6379.jpg',
      altText: '9_RITAKSHI_HOUSE_IMG_6379.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '172',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/9_RITAKSHI_HOUSE_IMG_6380.jpg',
      altText: '9_RITAKSHI_HOUSE_IMG_6380.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '173',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/9_RITAKSHI_HOUSE_IMG_6386.jpg',
      altText: '9_RITAKSHI_HOUSE_IMG_6386.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '174',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/9_RITAKSHI_HOUSE_IMG_6389.jpg',
      altText: '9_RITAKSHI_HOUSE_IMG_6389.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '175',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/9_RITAKSHI_HOUSE_IMG_6391.jpg',
      altText: '9_RITAKSHI_HOUSE_IMG_6391.jpg',
      width: 1641,
      height: 1080,
    },
    {
      id: '176',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/9_RITAKSHI_HOUSE_IMG_6411.jpg',
      altText: '9_RITAKSHI_HOUSE_IMG_6411.jpg',
      width: 1641,
      height: 1080,
    },
    {
      id: '177',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/9_RITAKSHI_HOUSE_IMG_6419.jpg',
      altText: '9_RITAKSHI_HOUSE_IMG_6419.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '178',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/9_RITAKSHI_HOUSE_IMG_6428.jpg',
      altText: '9_RITAKSHI_HOUSE_IMG_6428.jpg',
      width: 1641,
      height: 1080,
    },
    {
      id: '179',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/9_RITAKSHI_HOUSE_IMG_6437.jpg',
      altText: '9_RITAKSHI_HOUSE_IMG_6437.jpg',
      width: 1641,
      height: 1080,
    },
    {
      id: '180',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/9_RITAKSHI_HOUSE_IMG_6485.jpg',
      altText: '9_RITAKSHI_HOUSE_IMG_6485.jpg',
      width: 1641,
      height: 1080,
    },
    {
      id: '181',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/VILLA_IMG_9534.jpg',
      altText: 'VILLA_IMG_9534.jpg',
      width: 1920,
      height: 1266,
    },
    {
      id: '182',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/VILLA_IMG_9539.jpg',
      altText: 'VILLA_IMG_9539.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '183',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/VILLA_IMG_9556.jpg',
      altText: 'VILLA_IMG_9556.jpg',
      width: 1920,
      height: 1280,
    },
    {
      id: '184',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/VILLA_IMG_9558.jpg',
      altText: 'VILLA_IMG_9558.jpg',
      width: 1920,
      height: 1263,
    },
    {
      id: '185',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/VILLA_IMG_9564.jpg',
      altText: 'VILLA_IMG_9564.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '186',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/VILLA_IMG_9568.jpg',
      altText: 'VILLA_IMG_9568.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '187',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/VILLA_IMG_9647.jpg',
      altText: 'VILLA_IMG_9647.jpg',
      width: 1920,
      height: 1263,
    },
    {
      id: '188',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/VILLA_IMG_9670.jpg',
      altText: 'VILLA_IMG_9670.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '189',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/VILLA_IMG_9671.jpg',
      altText: 'VILLA_IMG_9671.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '190',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/VILLA_IMG_9672.jpg',
      altText: 'VILLA_IMG_9672.jpg',
      width: 1280,
      height: 1920,
    },
    {
      id: '191',
      title: '',
      description: '',
      url: 'https://s3.ap-south-1.amazonaws.com/siddheshsavantphotography.com/images/VILLA_IMG_9695.jpg',
      altText: 'VILLA_IMG_9695.jpg',
      width: 1280,
      height: 1920,
    },
  ] as IPhoto[];
